name: Release

on:
  push:
    tags:
      - "*"

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push api
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.api
          tags: bitmetro/helmsman-api:${{ github.ref_name }}

  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.client
          tags: bitmetro/helmsman-client:${{ github.ref_name }}